models.py
from flask_mongoengine import MongoEngine
import datetime

db = MongoEngine()

class Memo(db.EmbeddedDocument):
    tag = db.StringField(max_length=20)
    body = db.StringField(max_length=150)

class Post(db.Document):
    title = db.StringField(max_length=100, required=True)
    content = db.StringField(max_length=200, required=True)
    memo = db.EmbeddedDocumentField(Memo)
    created_at = db.DateTimeField(default=datetime.datetime.now)

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, Length


class PostForm(FlaskForm):
    title = StringField('タイトル',validators=[Required(), Length(1,80)])
    content = TextAreaField('本文',validators=[Required(), Length(1,180)])
    submit = SubmitField('保存')

class MemoForm(FlaskForm):
    tag = StringField("タグ", validators=[Length(1,20)])
    body = TextAreaField("メモ", validators=[Length(1,150)])
    submit = SubmitField('保存')

app.py
from init import create_app

app = create_app()



if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5555)

views.py
from flask import Flask, request, render_template, flash, redirect, url_for, Blueprint
from models import Memo, Post
from forms import MemoForm, PostForm
from flask_mongoengine import DoesNotExist


main = Blueprint('main', __name__)

@main.route('/')
def index():
    page = request.args.get("page", default=1, type=int)
    posts = Post.objects.order_by("-created_at").paginate(page=page, per_page=10).items
    return render_template('index.html', posts=posts)

@main.route('/add', methods=["GET", "POST"])
def add():
    form = PostForm()
    if form.validate_on_submit():
        Post(title=form.title.data, content=form.content.data).save()
        flash('post added!')
        return redirect(url_for(".index"))
    return render_template('add.html', form=form)

@main.route('/delete')
def delete():
    # id come from url param
    _id = request.args.get('id',type=str)
    try:
        post = Post.objects.get(id=_id)
    except DoesNotExist:
        flash('the post alredy not exist.')
        return redirect(url_for(".index"))
    post.delete()
    # post = Post(id).delete()
    flash("the post deleted")
    return redirect(url_for(".index"))

@main.route('/edit-memo/<string:_id>', methods=['GET', 'POST'])
def edit_memo(_id):
    form = MemoForm()
    post = Post.objects.get(id=_id)
    if form.validate_on_submit():
        post.memo.tag = form.tag.data
        post.memo.body = form.body.data
        post.save()
        return redirect(url_for(".index"))
    form.tag.data = post.memo.tag
    form.body.data = post.memo.body 
    return render_template('edit_memo.html', form=form, post=post)

@main.route('/create-memo/<string:_id>', methods=['GET', 'POST'])
def create_memo(_id):
    form = MemoForm()
    post = Post.objects.get(id=_id)
    if form.validate_on_submit():
        new_memo = Memo()
        new_memo.tag = form.tag.data
        new_memo.body = form.body.data
        post.memo = new_memo
        post.save()
        return redirect(url_for(".index"))
    return render_template('edit_memo.html', form=form, post=post)

templates/_post.html
<div class="post">
	<div class="columns">
		<div class="column">
			{% include '_postview.html' %}
		</div>
	</div>
	<a href="{{ url_for('main.delete', id=post.id) }}">
		<span class="label label-error">消去</span>
	</a>

	{% if post.memo %}
	<div class="popover popover-right">
		<span class="label label-success">メモ</span>
		<div class="popover-container">
			<div class="card">
				<div class="card-header">{{ post.memo.tag }}</div>
				<div class="card-body">{{ post.memo.body }}</div>
				<div class="card-footer">
					<a href="{{ url_for('main.edit_memo', _id=post.id) }}">
						<span class="label label-primary">編集</span>
					</a>
				</div>
			</div>
		</div>
	</div>
	{% endif %}

	{% if not post.memo %}
	<a href="{{ url_for('main.create_memo', _id=post.id) }}">
		<span class="label ">メモをつける</span>
	</a>
	{% endif %}

	
</div>

templates/_postview.html
<h3 class="post-title">
	{{ post.title }}
</h3>
<div class="post-body">
	<p>{{ post.content }}</p>
	<div class="post-date">
		<p>{{ post.created_at }}</p>
	</div>
</div>

templates/add.html
{% extends "layout.html" %}

{% block page_content %}
	<h3>ポストを追加する</h3>
	<form class="form-horizontal" action="#" method="POST">
		{{ form.csrf_token }}
		<div class="form-group">
			<div class="col-2">
				{{ form.title.label(class_="form-label") }}
			</div>
			<div class="col-8">
				{{ form.title(class="form-input", placeholder="Title") }}
				{% if form.title.errors %}
				<ul>
					{% for error in form.title.errors %}
					<li class="text-error">{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div class="form-group">
			<div class="col-2">
				{{ form.content.label(class_="form-label") }}
			</div>
			<div class="col-8">
				{{ form.content(class_="form-input", rows='10',  placeholder="Content") }}
				{% if form.content.errors %}
				<ul>
					{% for error in form.content.errors %}
					<li class="text-error">{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div class="form-group">
			<div class="col-2"> </div>
			<div class="col-8"> {{ form.submit(class_="btn btn-primary") }} </div>
		</div>
	</form>
{% endblock %}

templates/edit_memo.html
{% extends "layout.html" %}


{% block page_content %}
		{% include "_postview.html" %}
	<form class="form-horizontal" action="#" method="POST">
		{{ form.csrf_token }}
		<div class="form-group">
			<div class="col-2">
				{{ form.tag.label(class_="form-label") }}
			</div>
			<div class="col-8">
				{{ form.tag(class="form-input", placeholder="Title") }}
				{% if form.tag.errors %}
				<ul>
					{% for error in form.tag.errors %}
					<li class="text-error">{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div class="form-group">
			<div class="col-2">
				{{ form.body.label(class_="form-label") }}
			</div>
			<div class="col-8">
				{{ form.body(class_="form-input", rows='10',  placeholder="Content") }}
				{% if form.body.errors %}
				<ul>
					{% for error in form.body.errors %}
					<li class="text-error">{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div class="form-group">
			<div class="col-2"></div>
			<div class="col-8"> {{ form.submit(class_="btn btn-primary") }} </div>
		</div>
	</form>
<div class="columns">
	<div class="column col-8">
	</div>
	<!-- <div class="column col-4"> -->
		




	<!-- </div> -->
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block page_content %}
{% for post in posts %}
{% include "_post.html" %}
{% endfor %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MEMO</title>
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/icon">
	<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
	<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
	<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
	<style>
		.content {
			margin-top:50px;
			margin-bottom:10px;
			margin-right:10px;
			margin-left:10px;
		}
		.post {
			margin-bottom:80px;
		}
		.post-date {
			text-align:right;
		}
		.btn.btn-orange {
			background-color:#ffb700;
		}
		.post-title {
			text-align:center;
			margin-top:25px;
			margin-bottom:25px;
		}
		.flash-area {
			margin-top:10px;
			margin-bottom:10px;
		}
		.nav {
			padding: 10px;
		}
		.post-body {
			width: 90%;
			margin:auto;
		}
	</style>
</head>
<body>
<div class="content">
	<div class="container grid-lg">
		<div class=" off-canvas">
			<div class="off-canvas-sidebar">
				<ul class="nav">
					<li class="nav-item">
						<a href="{{ url_for('main.index') }}">
							<span class="icon icon-apps"></span>
							ホーム
						</a>
					</li>
					<li class="nav-item">
						<a href="{{ url_for('main.add') }}">
							<span class="icon icon-plus"></span>
							ポスト追加
						</a>
					</li>
				</ul>
			</div>
			<div class="off-canvas-content">
				<div class="columns">
					<div class="column col-11 col-mx-auto">
					{% with messages = get_flashed_messages() %}
						{% if messages %}
							{% for message in messages %}
							<div class="toast flash-area">{{ message }} </div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% block page_content %}
					{% endblock %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
</body>
</html>